//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Log_Id { get; set; }
        public int Software_Id { get; set; }
        public byte ErrorType { get; set; }
        public string ErrorMessage { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Software Software { get; set; }
    }
}
